services/userMangaService/demodj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('user/', include('userAccount.urls')),
    path('manga/', include('mangaApp.urls')),
    path('api/', include('apiUrls.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

services/userMangaService/home/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name = 'home')
]

services/userMangaService/mangaApp/urls.py
from django.urls import path, include, re_path
from . import views

app_name = 'mangaApp'

urlpatterns = [
    path('', views.index, name = 'home'),
    path('addManga/', views.addManga.as_view(), name = 'addManga'),
    path('addChapter/', views.addChapter.as_view(), name = 'addChapter'),
    path('mangaAutocomplete/', views.mangaAutocomplete, name = 'mangaAutocomplete'),
    path('<int:pk>/', views.mangaDetails, name = 'mangaDetails'),
    path('<int:mangaPk>/<int:chapterPk>/', views.chapterDetails, name = 'chapterDetails'),
]

services/userMangaService/userAccount/urls.py
from django.urls import path
from . import views

app_name = 'userAccount'

urlpatterns = [
    path('register/', views.registerUser.as_view(), name = 'registerUser'),
    path('login/', views.loginUser.as_view(), name = 'loginUser'),
    path('logout/', views.logoutUser, name = 'logoutUser'),
    path('info/', views.infoPage.as_view(), name = 'info'),
]

services/userMangaService/home/models.py
from django.db import models

# Create your models here.

services/userMangaService/home/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
	return render(request, 'home/index.html')

services/userMangaService/home/templates/home/base.html
<!DOCTYPE html>
<html>
<head>
	{% load static %}
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Home</title>
	<link rel="stylesheet" href="{% static 'home/style.css' %}">
</head>
<body>
	<h1>This is my fucking Homepage</h1>
	<div class = "Menu">
		<ul>
			<li><a href="{% url 'userAccount:loginUser' %}">Dang Nhap</a></li>
			<li><a href="{% url 'userAccount:registerUser' %}">Dang Ky</a></li>
			<li><a href="{% url 'mangaApp:home' %}">Doc Truyen</a></li>
			<li>Coi Phim</li>
		</ul>
	</div>

	<div class = "script">
		{% block script %}

		{% endblock %}
	</div>

	<div class = "content">
		{% block content %}

		{% endblock %}
	</div>

	<a href="{% url 'homepage:home' %}">Back To Homepage</a>
</body>
</html>

services/userMangaService/home/templates/home/index.html
{% extends 'home/base.html' %}
	{% block content %}
		<h2>This is my fucking index.html</h2>
	{% endblock %}