services/userMangaService/demodj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('user/', include('userAccount.urls')),
    path('manga/', include('mangaApp.urls')),
    path('api/', include('apiUrls.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

services/userMangaService/home/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name = 'home')
]

services/userMangaService/mangaApp/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.getRoutes),
    
    ### Manga url ###
    path('mangaList/', views.getMangasList),
    path('newManga/', views.addManga),
    path('<int:pk>/delete/', views.deleteManga),
    path('<int:pk>/', views.getMangaDetails),
    
    ### Chapter url ###
    path('<int:pk>/chapterList/', views.getChapters),
    path('<int:pk>/chapter/upload/', views.addChapter),
    path('<int:pk>/chapter/uploadMulti/', views.addMultiChapters),
    path('<int:pk>/<int:chapterId>/delete/', views.deleteChapter),
    path('<int:pk>/<int:chapterId>/', views.getImages),
    
    ### Album url ###
    path('albums/', views.getAlbums),
    path('albums/<int:albumId>/', views.getAlbumMangaList),
    path('albums/create/', views.createAlbum),
    path('albums/add/<int:albumId>/<int:mangaId>/', views.addAlbumManga),
    path('albums/remove/<int:albumId>/<int:mangaId>/', views.removeAlbumManga),
    path('albums/delete/<int:albumId>/', views.deleteAlbum),
    
    ### Favourite Manga url ###
    path('favourites/', views.getFavouriteMangas),
    path('favourites/add/', views.addFavouriteManga),
    path('favourites/remove/', views.removeFavouriteManga),
    
    ### Category url ###
    path('categoryList/', views.getCategoryList),
    
    ### Banner url ###
    path('bannerList/', views.getBannerList),
    
    ### Manga ranking ###
    path('topMangas/', views.getMangaRanking),
]

services/userMangaService/mangaApp/urls.py
from django.urls import path, include, re_path
from . import views

app_name = 'mangaApp'

urlpatterns = [
    path('', views.index, name = 'home'),
    path('addManga/', views.addManga.as_view(), name = 'addManga'),
    path('addChapter/', views.addChapter.as_view(), name = 'addChapter'),
    path('mangaAutocomplete/', views.mangaAutocomplete, name = 'mangaAutocomplete'),
    path('<int:pk>/', views.mangaDetails, name = 'mangaDetails'),
    path('<int:mangaPk>/<int:chapterPk>/', views.chapterDetails, name = 'chapterDetails'),
]

services/userMangaService/mangaApp/forms.py
from django import forms
from .models import Chapter, Manga, Picture, MangaPackage

class addChapterForm(forms.ModelForm):
    mangaNameAutocomplete = forms.CharField(label = 'MangaName', widget = forms.TextInput(
        attrs = {
            'class': 'mangaAutocomplete',
        }))
    
    class Meta:
        model = Chapter
        fields = ['mangaNameAutocomplete', 'mangaName', 'chapterZipData', 'index']
        widgets = {'mangaName': forms.HiddenInput()}
        
class addMangaPackageForm(forms.ModelForm):
    mangaNameAutocomplete = forms.CharField(label = 'MangaName', widget = forms.TextInput(
        attrs = {
            'class': 'mangaAutocomplete',
        }))
    
    class Meta:
        model = MangaPackage
        fields = ['mangaNameAutocomplete', 'mangaName', 'chapterZipData']
        widgets = {'mangaName': forms.HiddenInput()}

class addMangaForm(forms.ModelForm):
    class Meta:
        model = Manga
        fields = ['name', 'description']
        
class addImageForm(forms.ModelForm):
    class Meta:
        model = Picture
        fields = ['chapter', 'image']

services/userMangaService/mangaApp/api/views.py
import zipfile
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework import status

from mangaApp.models import Manga, Chapter, Picture, FavouriteManga, Category, Banner, DayViews, Album, MangaUserRating
from .serializers import BannerSerializer, ChapterSerializer, MangaSerializer, PictureSerializer, FavouriteMangaSerializer, CategorySerializer, MangaRankingSerializer, AlbumSerializer, MangaUserRatingSerializer
from django.core.files.images import ImageFile
from django.core.files import File as DjangoFile

#safe = False mean can use data by any languages like queryset of python to json data



####### Get Routes Of API #######
@api_view(['GET'])
def getRoutes(request):
    routes = [
        'GET /api/',
        'GET /api/mangaApp/mangaList/',
        'POST /api/mangaApp/newManga/',
        'DELETE /api/mangaApp/:id/delete/',
        'GET /api/mangaApp/:id',
        '',
        'GET /api/mangaApp/:id/chapterList/',
        'POST /api/mangaApp/:id/chapter/upload/',
        'POST /api/mangaApp/:id/chapter/uploadMulti/',
        'GET /api/mangaApp/:id/:chapterId/',
        'DELETE /api/mangaApp/:id/:chapterId/delete/'
        '',
        'GET /api/mangaApp/favourites/',
        'POST /api/mangaApp/favourites/add/',
        'DELETE /api/mangaApp/favourites/remove/',
        '',
        'GET /api/mangaApp/categoryList/',
        '',
        'Get /api/mangaApp/bannerList/',
    ]
    
    return Response(routes)



####### Manga handling #######
@api_view(['GET'])
def getMangasList(request):
    mangas = Manga.objects.all()
    #many = True mean the object we use is the list of items, = False if single item
    serializer = MangaSerializer(mangas, many = True)
    return Response(serializer.data)

@api_view(['GET'])
def getMangaDetails(request, pk):
    manga = Manga.objects.get(id = pk)
    serializer = MangaSerializer(manga, many = False)
    return Response(serializer.data)

@api_view(['POST'])
def addManga(request):
    data = request.data
    manga = Manga.objects.create(name = data['mangaName'], description = data['description'], cover = data['cover_image'])
    for item in data.getlist('categories'):
        category = Category.objects.get(id = item)
        manga.categories.add(category)
    
    serializer = MangaSerializer(manga, many = False)
    return Response(serializer.data)

@api_view(['DELETE'])
def deleteManga(request, pk):
    manga = Manga.objects.get(id = pk)
    manga.delete()
    return Response('Manga was deleted!!')



####### Chapter handling #######
@api_view(['GET'])
def getChapters(request, pk):
    manga = Manga.objects.get(id = pk)
    chapters = manga.chapter.all()
    serialzer = ChapterSerializer(chapters, many = True)
    return Response(serialzer.data)

@api_view(['GET'])
def getImages(request, pk, chapterId):
    chapter = Chapter.objects.get(mangaName__id = pk, id = chapterId)
    pictures = chapter.image.all()
    serializer = PictureSerializer(pictures, many = True)
    return Response(serializer.data)

@api_view(['POST'])
def addChapter(request, pk):
    manga = Manga.objects.get(id = pk)
    manga.save()
    chapter = Chapter.objects.create(mangaName = manga, chapterZipData = request.data['chapterData'], index = request.data['chapterId'])
    handleUploadedChapter(chapter.chapterZipData, chapter)
    serializer = ChapterSerializer(chapter, many = False)
    return Response(serializer.data)

@api_view(['POST'])
def addMultiChapters(request, pk):
    manga = Manga.objects.get(id = pk)
    manga.save()
    handleUploadedMangaPackage(request.data['chapterData'], manga)
    chapters = Chapter.objects.filter(mangaName__id = pk)
    serializer = ChapterSerializer(chapters, many = True)
    return Response(serializer.data)

def handleUploadedMangaPackage(myZipFile, mangaName):                                                                                                 
    with zipfile.ZipFile(myZipFile, 'r') as data_zip:
        files = data_zip.namelist()
        for i in range(len(files)):
            chapterIndex = files[i] 
            chapterIndex = chapterIndex.replace('Chapter ', '')
            chapterIndex = int(chapterIndex.replace('.zip', ''))
            
            childZipData = DjangoFile(data_zip.open(files[i], mode = 'r'))
            
            try:
                chapter = Chapter.objects.get(mangaName = mangaName, index = chapterIndex)
            except Chapter.DoesNotExist:
                Chapter.objects.create(mangaName = mangaName, chapterZipData = childZipData, index = chapterIndex)
                
            handleUploadedChapter(childZipData, Chapter.objects.latest('id'))

def handleUploadedChapter(myZipFile, chapterIndex):                                                                                                 
    with zipfile.ZipFile(myZipFile, 'r') as data_zip:
        files = data_zip.namelist()
        
        for i in range(len(files)):
            Picture.objects.create(chapter = chapterIndex, image = ImageFile(data_zip.open(files[i])))

@api_view(['DELETE'])
def deleteChapter(request, pk, chapterId):
    chapter = Chapter.objects.get(mangaName__id = pk, id = chapterId)
    chapter.delete()
    return Response('Chapter was deleted!')
            
            
            
            
####### Categories Handling #######
@api_view(['GET'])
def getCategoryList(request):
    categories = Category.objects.all()
    serializer = CategorySerializer(categories, many = True)
    return Response(serializer.data)

@api_view(['POST'])
def addCategory(request):
    category, created = Category.objects.get_or_create(name = request.data['name'])
    serializer = CategorySerializer(category, many = False)
    return Response(serializer.data)
    
    
    
    
####### Banner Handling #######       
@api_view(['GET'])
def getBannerList(request):
    bannerList = Banner.objects.all()
    serializer = BannerSerializer(bannerList, many = True)
    return Response(serializer.data)
       
       
    
       
####### Albums Handling #######
@api_view(['GET'])
@permission_classes([IsAuthenticated])
def getAlbums(request):
    user = request.user
    albumList = user.albums.all()
    serializer = AlbumSerializer(albumList, many = True)
    return Response(serializer.data)

@api_view(['GET'])
@permission_classes([IsAuthenticated])
def getAlbumMangaList(request, albumId):
    user = request.user
    album = user.albums.get(pk = albumId)
    mangaList = album.mangaList.all()
    serializer = MangaSerializer(mangaList, many = True)
    return Response(serializer.data)

@api_view(['POST'])
@permission_classes([IsAuthenticated])
def createAlbum(request):
    user = request.user
    data = request.data
    newAlbum, created = Album.objects.get_or_create(name = data['name'], user = user)
    
    serializer = AlbumSerializer(newAlbum, many = False)
    return Response(serializer.data)

@api_view(['POST'])
@permission_classes([IsAuthenticated])
def addAlbumManga(request, albumId, mangaId):
    user = request.user
    album = user.albums.get(pk = albumId)
    manga = Manga.objects.get(pk = mangaId)
    
    #Favourite List
    if albumId == user.albums.get(name = "Favourites"): 
        manga.favourites += 1
        
    album.mangaList.add(manga)
    serializer = AlbumSerializer(album, many = False)
    return Response(serializer.data)

@api_view(['DELETE'])
@permission_classes([IsAuthenticated])
def deleteAlbum(request, albumId):
    user = request.user
    album = user.albums.get(pk = albumId)
    
    #Only Favourite can't be deleted
    if (album.name != "Favourites"):
        album.delete()
    
    serializer = AlbumSerializer(user.albums, many = True)
    return Response(serializer.data)  

@api_view(['DELETE'])
@permission_classes([IsAuthenticated])
def removeAlbumManga(request, albumId, mangaId):
    user = request.user
    album = user.albums.get(pk = albumId)
    manga = album.mangaList.get(pk = mangaId)
    
    album.mangaList.remove(manga)
    
    #Favourites
    if (album.name == "Favourites"):
        manga.favourites -= 1
    
    serializer = AlbumSerializer(album, many = False)
    return Response(serializer.data)     
            
            
            
####### Favourite Handling #######
@api_view(['GET'])
@permission_classes([IsAuthenticated])
def getFavouriteMangas(request):
    user = request.user
    favoMangas = user.favourMangas
    serializer = FavouriteMangaSerializer(favoMangas, many = False)
    return Response(serializer.data)

@api_view(['POST'])
@permission_classes([IsAuthenticated])
def addFavouriteManga(request):
    user = request.user
    manga = Manga.objects.get(id = request.data['mangaId'])
    Manga.objects.filter(id = request.data['mangaId']).update(favourites = manga.favourites + 1)
    user.favourMangas.mangas.add(manga)
    
    favoMangas = user.favourMangas
    serializer = FavouriteMangaSerializer(favoMangas, many = False)
    return Response(serializer.data)

@api_view(['DELETE'])
@permission_classes([IsAuthenticated])
def removeFavouriteManga(request):
    user = request.user
    manga = Manga.objects.get(id = request.data['mangaId'])
    Manga.objects.filter(id = request.data['mangaId']).update(favourites = manga.favourites - 1)
    user.favourMangas.mangas.remove(manga)
    
    favoMangas = user.favourMangas
    serializer = FavouriteMangaSerializer(favoMangas, many = False)
    return Response(serializer.data)


####### Manga Optional Stuff Handling #######
@api_view(['POST'])
def addView(request, pk):
    manga = Manga.objects.get(id = pk)
    Manga.objects.filter(id = pk).update(views = manga.views + 1)
    day = request.data['day']
    
    dayViews, created = DayViews.objects.get_or_create(manga = manga, day = day)
    dayViews.views += 1
    dayViews.save()
    
    return Response(status = status.HTTP_200_OK)

@api_view(['GET'])
def getMangaRanking(request):

services/userMangaService/mangaApp/templates/mangaApp/addChapter.html
{% extends 'home/base.html' %}
    {% block script %}
        <link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
        <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
        <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
        <script>
            $( function() {
                $(".mangaAutocomplete").autocomplete({
                    source: '{% url 'mangaApp:mangaAutocomplete' %}',
                    minLength: 0,
                });

                $( "#mangaName1" ).autocomplete({
                    source: '{% url 'mangaApp:mangaAutocomplete' %}',
                    minLength: 0,
                });
            } );
        </script>
    {% endblock %}

	{% block content %}
        <h2>Add Multiple Chapters</h2>
        <form action="{% url 'mangaApp:addChapter' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{mangaPackForm.as_p}}

            <input type="submit">
        </form>

        <h2>Add Single Chapter</h2>
        <form action="{% url 'mangaApp:addChapter' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{chapForm.as_p}}

            <input type="submit">
        </form>

	{% endblock %}

services/userMangaService/mangaApp/templates/mangaApp/addManga.html
{% extends 'home/base.html' %}
	{% block content %}
        <form action="{% url 'mangaApp:addManga' %}" method="POST">
            {% csrf_token %}
            {{addMangaForm.as_p}}

            <input type="submit">
        </form>
	{% endblock %}

services/userMangaService/mangaApp/templates/mangaApp/chapter.html
{% extends 'home/base.html' %}
	{% block content %}
        <div>
                <a href="{% url 'mangaApp:chapterDetails' mangaId prevChap %}">Previous Chapter</a>
                <a href="{% url 'mangaApp:chapterDetails' mangaId nextChap %}">Next Chapter</a>
        </div>
        {% for pic in chapter.image.all %}
                <p><img src="{{pic.image.url}}" alt=""></p>
        {% endfor %}

        <div>
                <a href="{% url 'mangaApp:chapterDetails' mangaId prevChap %}">Previous Chapter</a>
                <a href="{% url 'mangaApp:chapterDetails' mangaId nextChap %}">Next Chapter</a>
        </div>
	{% endblock %}

services/userMangaService/mangaApp/templates/mangaApp/errorForm.html
{% extends 'home/base.html' %}
	{% block content %}
        <h1>YOUR FORM IS FUCKING INVALID!!!</h1>
	{% endblock %}

services/userMangaService/mangaApp/templates/mangaApp/index.html
{% extends 'home/base.html' %}
	{% block content %}
        <div><a href="{% url 'mangaApp:addManga' %}">Add Manga</a></div>
        <div><a href="{% url 'mangaApp:addChapter' %}">Add Chapter</a></div>
        {% for manga in mangaList %}
            <a href = "{{manga.id}}/">{{manga.name}}</a>
            <ul>
                {% for chapter in manga.chapter.all %}
                        <li><a href="{{manga.id}}/{{chapter.id}}/">{{chapter.index}}</a></li>
                {% endfor %}
            </ul>
        {% endfor %}
	{% endblock %}

services/userMangaService/mangaApp/templates/mangaApp/manga.html
{% extends 'home/base.html' %}
	{% block content %}
        <h1>MY FUCKING MANGA PAGE</h1>
        <h3>This fucking Manga is {{manga.name}} </h3>
        {% for chapter in manga.chapter.all %}
                <a href="{{chapter.id}}/">Chapter {{chapter.index}}</a>
        {% endfor %}
	{% endblock %}