services/userMangaService/demodj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('user/', include('userAccount.urls')),
    path('manga/', include('mangaApp.urls')),
    path('api/', include('apiUrls.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

services/userMangaService/home/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name = 'home')
]

services/userMangaService/userAccount/api/urls.py
from django.urls import path
from . import views

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
  path('token/', views.MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
  path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
  path('userData/', views.getUserData),
]

services/userMangaService/userAccount/urls.py
from django.urls import path
from . import views

app_name = 'userAccount'

urlpatterns = [
    path('register/', views.registerUser.as_view(), name = 'registerUser'),
    path('login/', views.loginUser.as_view(), name = 'loginUser'),
    path('logout/', views.logoutUser, name = 'logoutUser'),
    path('info/', views.infoPage.as_view(), name = 'info'),
]

services/userMangaService/userAccount/models.py
from django.db import models

# Create your models here.

services/userMangaService/userAccount/forms.py
from django import forms

class registerForm(forms.Form):
	username = forms.CharField(max_length = 20)
	email = forms.EmailField()
	password = forms.CharField(max_length = 20, widget = forms.PasswordInput)

class loginForm(forms.Form):
	username = forms.CharField()
	password = forms.CharField(max_length = 20, widget = forms.PasswordInput)

services/userMangaService/userAccount/api/views.py
from django.contrib.auth.models import User
from django.db.models import Q

from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from rest_framework.decorators import api_view, permission_classes
from rest_framework import status

from mangaApp.models import FavouriteManga
from .serializers import UserSerializer

####### Customized Token Information #######
from rest_framework_simplejwt.serializers import TokenObtainPairSerializer
from rest_framework_simplejwt.views import TokenObtainPairView

class MyTokenObtainPairSerializer(TokenObtainPairSerializer):
    @classmethod
    def get_token(cls, user):
        token = super().get_token(user)

        # Add custom claims
        token['username'] = user.username
        token['isSuperuser'] = user.is_superuser
        # ...

        return token

class MyTokenObtainPairView(TokenObtainPairView):
    serializer_class = MyTokenObtainPairSerializer

@api_view(['GET'])
@permission_classes([IsAuthenticated])
def getUserData(request):
    serializer = UserSerializer(request.user, many = False)
    return Response(serializer.data)

services/userMangaService/userAccount/views.py
from django.shortcuts import render, redirect
from .forms import registerForm, loginForm
from django.views import View
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required #normal
from django.contrib.auth.mixins import LoginRequiredMixin #class based-view


# Create your views here.

class registerUser(View):
	def get(self, request):
		rF = registerForm
		return render(request, 'userAccount/register.html', {'rF' : rF})

	def post(self, request):
		username = request.POST['username']
		email = request.POST['email']
		password = request.POST['password']

		user = User.objects.create_user(username, email, password)
		user.save()
		return HttpResponse('saved!!')

class loginUser(View):
	def get(self, request):
		if request.user.is_authenticated:
			return redirect('userAccount:info')

		lF = loginForm
		return render(request, 'userAccount/login.html', {'lF': lF})

	def post(self, request):
		username = request.POST['username']
		password = request.POST['password']

		user = authenticate(request, username = username, password = password)

		if user is not None:
			login(request, user)
			return redirect('userAccount:info')
		else:
			return HttpResponse('Fuck you, wrong username or password!!!')

def logoutUser(request):
	logout(request)
	return redirect('userAccount:loginUser')

class infoPage(LoginRequiredMixin, View):
	login_url = '/user/login/'
	def get(self, request):
		return render(request, 'userAccount/info.html')

		

services/userMangaService/userAccount/templates/userAccount/info.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>User Information</title>
	<link rel="stylesheet" href="">
</head>
<body>
	<h1>This is your fucking Info Page</h1>
	<div> <a href="{% url 'userAccount:logoutUser' %}">Logout</a> </div>
	<a href="{% url 'homepage:home' %}">Back To Homepage</a>
</body>
</html>

services/userMangaService/userAccount/templates/userAccount/login.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>LoginForm</title>
	<link rel="stylesheet" href="">
</head>
<body>
	<h1>This is Fucking Login Form</h1>
	<form action="{% url 'userAccount:loginUser' %}" method="POST">
		{% csrf_token %}
		{{lF.as_p}}

		<input type="submit">
	</form>

	<a href="{% url 'homepage:home' %}">Back To Homepage</a>
</body>
</html>

services/userMangaService/userAccount/templates/userAccount/register.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>RegisterForm</title>
	<link rel="stylesheet" href="">
</head>
<body>
	<h1>This is Register Form</h1>
	<form action="{% url 'userAccount:registerUser' %}" method="POST">
		{% csrf_token %}
		{{rF.as_p}}

		<input type="submit">
	</form>

	<a href="{% url 'homepage:home' %}">Back To Homepage</a>
</body>
</html>